### ISSUE TITLE
ROADMAP : feature & discussion

### ISSUE THREAD

**Issue by r17x** [ri7nz/x-pass-plugin#4]
This is plugin basically just a "wrapper" for CLI tool `pass` and have capability to use in GUI, especially in your menu bar (powered by Xbar). So, I write a list for possibility to "wrap" command or sub-command from `pass` to be a good feature in graphical usage:

- [x] `pass list`: have been implemented (show list menu in menu-bar) (first release)
  - [x] show lists with sub-menu for categorized by `directory` name (#3) by @rririanto 
- [x] `pass -c <param>`: have been implemented (when user click an item in the list of menu-bar)
- [ ]  `pass generate <param>`: not implemented (for generate new password) 
- [ ]  `pass remove <param>`: not implemented (for removed a password)
- [ ]  `sync information`: some `pass` user is using `git remote hosted` for store the all encrypted pass file 

> if you want to implement some from the list, choose 1 and make 1 merge request for the feature 🙌

If you interest, feel free for ask or put something comment ! 🙌

Thank you!
